### PR TITLE
Patch v1.0.1

### PR DESCRIPTION
**Pull request by KeidsID**
### Changed

- Better "Last season section" UI on mobile device.
- Better "image at carousel" UI on tablet/dekstop device.
- Better navigation UX and performance.

### CODE REVIEW

**Comment by KeidsID** [comment]
[Better [kIsMobile] constant](https://github.com/flutter/flutter/issues/80505#issuecomment-821817704)

**Comment by KeidsID** [comment]
v1.0.0 status are on review on play store. Thats why this PR version are v1.0.1+2

**Review by KeidsIDAlt — CHANGES_REQUESTED** [review]
update the `kIsMobile` constant.

**Comment by KeidsIDAlt** [comment]
Please fix the carousel tests.

**Comment by KeidsID** [comment]
Preview link: https://screen-pal-preview.netlify.app

**Review by KeidsIDAlt — APPROVED** [review]
💯

**Review by KeidsIDAlt — APPROVED** [review]

**Review by KeidsIDAlt — APPROVED** [review]

**Review by KeidsIDAlt — APPROVED** [review]
😪

**Review by KeidsIDAlt — APPROVED** [review]
😡

**Review by KeidsIDAlt — APPROVED** [review]
🥇

**Review by KeidsIDAlt — APPROVED** [review]
lmao pisan lamana

**Pull request merged**
