### PR TITLE
feat-credits

### PR DESCRIPTION
**Pull request by KeidsID**
### Added

- Movies and Tv Shows credits (casts and crews).

### Patch

- Project structures changes.

### CODE REVIEW

**Review by KeidsIDAlt — COMMENTED** [review]
Where's the crews list?

**Review by KeidsID — COMMENTED** [review]
maknyus

**Review by KeidsIDAlt — APPROVED** [review]
Maknyus

**Review by KeidsIDAlt — APPROVED** [review]
gile

**Pull request merged**
